name: CI
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name != 'main' || github.sha }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
          standalone: true
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      - run: pnpm prettier:check
      - run: pnpm build
  test-enterprise:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]
          standalone: true
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
      - run: pnpm prettier:check
      - run: pnpm build:enterprise
